title: Joseline Franco, MPH
logo: /assets/img/logo.png
description: Hello! My name is Joseline. I am a Data Ninja and a Viz Wizard!
<br><br>
  <a href="https://www.linkedin.com/in/joseline-franco/">👔 LinkedIn</a>
show_downloads: false
theme: jekyll-theme-minimal
